### ISSUE TITLE
Undefined method perform_later

### ISSUE THREAD

**Issue by Toucouleur66** [sidekiq-cron/sidekiq-cron#430] opened 2023-10-23 08:59 UTC
Hello

for ages I was using a branch set at https://github.com/citusdata/sidekiq-cron 
with `branch: "hotfix/pipelining_depreciation"`

but for some reason they removed this fix. So for now I update to 1.10.1 version and now I have this issue I really do not understand:
```
ERROR: CRON JOB: undefined method `perform_later' for #<Sidekiq::Worker::Setter:0x00007ffb1aec5898>
Did you mean?  perform_at
ERROR: CRON JOB: /.rvm/gems/ruby-2.7.8/gems/sidekiq-cron-1.10.1/lib/sidekiq/cron/job.rb:97:in `enqueue_active_job'
WARN: NoMethodError: undefined method `perform_later' for #<Sidekiq::Worker::Setter:0x00007ffb1aec5898>
Did you mean?  perform_at
WARN: /.rvm/gems/ruby-2.7.8/gems/sidekiq-cron-1.10.1/lib/sidekiq/cron/job.rb:97:in `enqueue_active_job'
```

our YAML file is set like this:

```default: &default
  track_status:
    # Every 2 minutes
    cron: "*/2 * * * *"
    class: "TrackStatusJob"
    queue: track_status
    date_as_argument: true # add the time of execution as last argument of the perform method
    active_job: true  # enqueue job through rails 4.2+ active job interface  
  scene_status:
    cron: "*/15 * * * *"
    class: "SceneStatusJob"
    queue: default    

development:
  <<: *default
  ```
  
  What could have we done wrong?
  
  Thanks

**Comment by markets** [comment] 2023-10-24 11:08
Hello @Toucouleur66, 

Sorry with this info you provided we can't debug further, the problem can be caused by several things (even other gems or versions in your app, unrelated to `sidekiq-cron`). Could you please provide a failing test in our suite or minimal app that reproduces the error?

The only weird thing that I see in your snippet is:

```
development:
  <<: *default
```

Are you sure you need this YAML alias here?

**Comment by sandip-mane** [comment] 2023-11-21 05:48
@Toucouleur66 please let us know if the issue is solved, if not, you could create a sample repo with a similar config where this issue happens and we could look into it.

**Comment by obie** [comment] 2024-01-14 01:06
I'm getting the same error today with version 1.12.0

```
NoMethodError: undefined method `perform_later' for #<Sidekiq::Job::Setter:0x00007f5cb43d4d30 
@klass=PeriodicStatsJob, @opts={"queue"=>"low_priority_queue"}> klass_const.set(queue: 
@queue).perform_later(*enqueue_args) ^^^^^^^^^^^^^^ Did you mean? perform_at
```

I traced it to having a Job which is _not_ an ActiveJob derived class marked as active_job in the configuration.

**Comment by markets** [comment] 2024-01-14 16:58
Hi @obie, that seems weird 🤔 

Could you please provide a failing test? This is the code that is used to detect AJ jobs:

https://github.com/sidekiq-cron/sidekiq-cron/blob/8a04c08ab1819d7f97070c9169bbbe14296c8286/lib/sidekiq/cron/job.rb#L85-L89

So, if you are not setting the `active_job` via configuration or your job is not an AJ subclass, the job is enqueued via the Sidekiq interface:

https://github.com/sidekiq-cron/sidekiq-cron/blob/8a04c08ab1819d7f97070c9169bbbe14296c8286/lib/sidekiq/cron/job.rb#L67-L71

**Closed** 2024-03-21 23:25 UTC
Labels: wontfix
