### ISSUE TITLE
Date::Errorvendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:609

### ISSUE THREAD

**Issue by farooqch11** [sidekiq-cron/sidekiq-cron#397] opened 2023-02-20 18:22 UTC
```
vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:611:in `parse': invalid date (Date::Error)
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:611:in `rescue in parse_enqueue_time'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:608:in `parse_enqueue_time'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:284:in `initialize'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:222:in `new'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:222:in `block in all'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:220:in `collect'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:220:in `all'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/poller.rb:22:in `enqueue'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/scheduled.rb:99:in `block in start'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:8:in `watchdog'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:17:in `block in safe_thread'

Caused by: vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:609:in `strptime': invalid date (Date::Error)
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:609:in `parse_enqueue_time'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:284:in `initialize'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:222:in `new'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:222:in `block in all'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:220:in `collect'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/job.rb:220:in `all'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-cron-1.9.1/lib/sidekiq/cron/poller.rb:22:in `enqueue'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/scheduled.rb:99:in `block in start'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:8:in `watchdog'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:17:in `block in safe_thread'
```

getting this error randomly after some time, cron-tab on sidekiq UI also breaks 

also when in production console i try to run **Sidekiq::Cron::Job.all** same errors being thrown again.  pleasse help me to find. we have almost 4000 jobs in cron which are dynamic, trying to find issue

**Comment by farooqch11** [comment] 2023-02-20 18:26
if i flush Redis and create fresh list of jobs through my code it works fine.

**Comment by markets** [comment] 2023-02-20 19:24
Hello @farooqch11 

I think this is related to this (still not merged) patch: #397

**Comment by farooqch11** [comment] 2023-02-20 20:12
@markets  patch is redirecting to this issue

**Comment by farooqch11** [comment] 2023-02-20 20:12
how can i get this fixed or i need to use sidekiq pro ? please help

**Comment by markets** [comment] 2023-02-20 20:21
oops! yes sorry, updated link (-> #354)!

You can try the patch posted in that ☝🏼 issue or as a workaround, change your machine/container/app to use EN language (as it seems the be root of the problem).

**Comment by farooqch11** [comment] 2023-02-20 20:30
Eng language where  in sidekiq configs ? @markets

**Comment by markets** [comment] 2023-02-20 20:58
The problem is: when your app enqueues jobs, those are queued with "localized" dates (see the screenshot in #354). So, you should somehow force a time-zone that `DateTime.parse('date')` can parse properly. But I'm not sure if this can be "forced" only for Sidekiq Cron without affecting your whole app. 

Maybe you can try @ryotarai's fork for now, or create your own updated fork and apply that patch. Unfortunately #354 is still not ready to be merged (there are some pending comments and git conflicts to be addressed).

**Comment by farooqch11** [comment] 2023-02-20 22:20
to try his fork i need to mention branch while installing gem ?

**Comment by farooqch11** [comment] 2023-02-20 22:26
i tried to use his  branch  `gem 'sidekiq-cron', git: 'https://github.com/ryotarai/sidekiq-cron.git'` but its not building, error 

```
Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     NoMethodError: undefined method `options' for Sidekiq:Module
remote:  !     /tmp/build_febdf89d/vendor/bundle/ruby/3.0.0/bundler/gems/sidekiq-cron-2720631e53b7/lib/sidekiq/options.rb:6:in `[]'
```


i think we might need to move to some other solution

**Comment by markets** [comment] 2023-02-20 22:38
That's because that branch seems to be outdated and probably doesn't work with your current Sidekiq version, so I think you should try to create your own updated fork (fork current master and apply these changes: https://github.com/sidekiq-cron/sidekiq-cron/pull/354/files).

**Comment by farooqch11** [comment] 2023-02-22 11:28
```
endor/bundle/ruby/3.0.0/gems/redis-client-0.12.1/lib/redis_client/command_builder.rb:37:in `block in generate': Unsupported command argument type: Time (TypeError)
    from vendor/bundle/ruby/3.0.0/gems/redis-client-0.12.1/lib/redis_client/command_builder.rb:28:in `map!'
    from vendor/bundle/ruby/3.0.0/gems/redis-client-0.12.1/lib/redis_client/command_builder.rb:28:in `generate'
    from vendor/bundle/ruby/3.0.0/gems/redis-client-0.12.1/lib/redis_client.rb:207:in `call'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/redis_client_adapter.rb:27:in `method_missing'
    from vendor/bundle/ruby/3.0.0/bundler/gems/sidekiq-cron-2ea739640b7c/lib/sidekiq/cron/job.rb:475:in `block in save_last_enqueue_time'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/config.rb:156:in `block in redis'
    from vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
    from vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
    from vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
    from vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
    from vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/config.rb:153:in `redis'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq.rb:73:in `redis'
    from vendor/bundle/ruby/3.0.0/bundler/gems/sidekiq-cron-2ea739640b7c/lib/sidekiq/cron/job.rb:473:in `save_last_enqueue_time'
    from vendor/bundle/ruby/3.0.0/bundler/gems/sidekiq-cron-2ea739640b7c/lib/sidekiq/cron/job.rb:72:in `enque!'
    from vendor/bundle/ruby/3.0.0/bundler/gems/sidekiq-cron-2ea739640b7c/lib/sidekiq/cron/job.rb:40:in `test_and_enque_for_time!'
    from vendor/bundle/ruby/3.0.0/bundler/gems/sidekiq-cron-2ea739640b7c/lib/sidekiq/cron/poller.rb:36:in `enqueue_job'
    from vendor/bundle/ruby/3.0.0/bundler/gems/sidekiq-cron-2ea739640b7c/lib/sidekiq/cron/poller.rb:23:in `block in enqueue'
    from vendor/bundle/ruby/3.0.0/bundler/gems/sidekiq-cron-2ea739640b7c/lib/sidekiq/cron/poller.rb:22:in `each'
    from vendor/bundle/ruby/3.0.0/bundler/gems/sidekiq-cron-2ea739640b7c/lib/sidekiq/cron/poller.rb:22:in `enqueue'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/scheduled.rb:99:in `block in start'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:8:in `watchdog'
    from vendor/bundle/ruby/3.0.0/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:17:in `block in safe_thread'
```


@markets  this error is happening with my custom fork  here
https://github.com/sidekiq-cron/sidekiq-cron/compare/master...farooqch11:sidekiq-cron:master

**Closed** 2023-03-02 15:08 UTC
